PREFIX c3po: <http://www.esciencedatafactory.com/C3PO/c3po.owl#>
SELECT ?wpName (SUM(?personMonth) AS ?personMonths)
WHERE {
  ?project a c3po:C3PO_0000101 ; c3po:C3PO_0000337 ?projectName .
  ?ts a c3po:C3PO_0000107 ;
      c3po:C3PO_0000206 ?project ;
      c3po:C3PO_0000217 ?task ;
      c3po:C3PO_0000202 ?emp ;
      c3po:C3PO_0000301 ?hours ;
      c3po:C3PO_0000347 ?tsDate .
  FILTER(!BOUND(?from) || SUBSTR(STR(?tsDate), 1, 7) >= SUBSTR(STR(?from), 1, 7))
  FILTER(!BOUND(?to) || SUBSTR(STR(?tsDate), 1, 7) <= SUBSTR(STR(?to), 1, 7))
  ?task c3po:C3PO_0000213 ?wp .
  ?wp c3po:C3PO_0000338 ?wpName .
  ?emp c3po:C3PO_0000312 ?annualProductiveHours .
  FILTER(?annualProductiveHours > 0)
  BIND(?hours / (?annualProductiveHours / 12) AS ?personMonth)
}
GROUP BY ?wp ?wpName
ORDER BY ?wpName
