PREFIX c3po: <http://www.esciencedatafactory.com/C3PO/c3po.owl#>
SELECT DISTINCT ?empName
WHERE {
  ?project a c3po:C3PO_0000101 ; c3po:C3PO_0000337 ?projectName .
  ?ts a c3po:C3PO_0000107 ;
      c3po:C3PO_0000206 ?project ;
      c3po:C3PO_0000202 ?emp ;
      c3po:C3PO_0000347 ?tsDate .
  FILTER(!BOUND(?from) || SUBSTR(STR(?tsDate), 1, 7) >= SUBSTR(STR(?from), 1, 7))
  FILTER(!BOUND(?to) || SUBSTR(STR(?tsDate), 1, 7) <= SUBSTR(STR(?to), 1, 7))
  ?emp c3po:C3PO_0000340 ?empName .
}
ORDER BY ?empName
