PREFIX c3po: <http://www.esciencedatafactory.com/C3PO/c3po.owl#>

SELECT DISTINCT ?employeeName WHERE {
  ?project a c3po:C3PO_0000101 ; c3po:C3PO_0000337 "FAIR-IMPACT" .
  ?ts a c3po:C3PO_0000107 ;
      c3po:C3PO_0000206 ?project ;
      c3po:C3PO_0000202 ?employee .
  ?employee c3po:C3PO_0000340 ?employeeName .
}
