PREFIX c3po: <http://www.esciencedatafactory.com/C3PO/c3po.owl#>

SELECT ((SUM(?grossSalary) + SUM(?patronalContribution)) AS ?annualPersonnelCost)
       (SUM(?grossSalary) AS ?totalSalaryGross)
       (SUM(?patronalContribution) AS ?totalPatronalContribution)
WHERE {
  ?emp a c3po:C3PO_0000105 ; c3po:C3PO_0000340 "Employe1" .
  ?payslip a c3po:C3PO_0000111 ;
             c3po:C3PO_0000205 ?emp ;
             c3po:C3PO_0000313 ?grossSalary ;
             c3po:C3PO_0000314 ?patronalContribution ;
             c3po:C3PO_0000330 ?yearMonth .

  FILTER(STRSTARTS(STR(?yearMonth), "2025"))
}
