PREFIX c3po: <http://www.esciencedatafactory.com/C3PO/c3po.owl#>

SELECT ?rpName ?startDate ?endDate
WHERE {
  ?project a c3po:C3PO_0000101 ; c3po:C3PO_0000337 "FAIR-IMPACT" .
  ?rp a c3po:C3PO_0000109 ;
      c3po:C3PO_0000204 ?project ;
      c3po:C3PO_0000341 "ERP1" ;
      c3po:C3PO_0000341 ?rpName ;
      c3po:C3PO_0000332 ?startDate ;
      c3po:C3PO_0000335 ?endDate .
}
