PREFIX c3po: <http://www.esciencedatafactory.com/C3PO/c3po.owl#>

SELECT ?city ?country
WHERE {
  ?project a c3po:C3PO_0000101 ; c3po:C3PO_0000337 "FAIR-IMPACT" .
  ?travel a c3po:C3PO_0000108 ;
          c3po:C3PO_0000214 ?project ;
          c3po:C3PO_0000318 ?purpose ;
          c3po:C3PO_0000306 ?city ;
          c3po:C3PO_0000305 ?country .
  FILTER(?purpose = "Dagstuhl Workshop 2023")
}
