PREFIX c3po: <http://www.esciencedatafactory.com/C3PO/c3po.owl#>

SELECT ?purpose
WHERE {
  ?project a c3po:C3PO_0000101 ; c3po:C3PO_0000337 "FAIR-IMPACT" .
  ?rp a c3po:C3PO_0000109 ; c3po:C3PO_0000341 "ERP2" ;
      c3po:C3PO_0000332 ?rpStart ; c3po:C3PO_0000335 ?rpEnd .

  ?travel a c3po:C3PO_0000108 ;
          c3po:C3PO_0000214 ?project ;
          c3po:C3PO_0000318 ?purpose ;
          c3po:C3PO_0000333 ?startDate .
  FILTER(?startDate >= ?rpStart && ?startDate <= ?rpEnd)
}
