PREFIX ex: <https://example.org/eu-expense#>
SELECT ?expense ?description ?amount ?acronym
WHERE {
  ?project a ex:C02 ; ex:P09 ?acronym .
  ?workPackage ex:P02 ?project .
  ?expense a ex:C06 ; ex:P17 false ; ex:P16 ?description ; ex:P14 ?amount ; ex:P04 ?workPackage .
}
ORDER BY DESC(?amount)
