PREFIX ex: <https://example.org/eu-expense#>
SELECT ?expense ?description ?amount ?acronym
WHERE {
  ?project a ex:EuropeanProject ; ex:acronym ?acronym .
  ?workPackage ex:belongsToProject ?project .
  ?expense a ex:Expense ; ex:eligible false ; ex:description ?description ; ex:amount ?amount ; ex:chargedToWorkPackage ?workPackage .
}
ORDER BY DESC(?amount)
